MyEbayBtn = "//*[@class='gh-eb-li-a gh-rvi-menu']"
MessageBtn = "//a[text()=' Messages']"
AllMessageBtn = "//*[@id='all_unread_c']/parent::li[@aria-current='true']"
Checkbox = "//*[@name='LineID']"
CheckboxAll = "//*[@id='chkbox-master']"
AllMsg = "//*[@id='emailRowView']//tr[starts-with(@class,'msg')]//*[@admin]"
BackInbox = "//*[@id='msg-header1']//*[@class='backlink link-align']"
DelBtn = "//*[@id='del-btn']/button"
TrashBtn = "//*[@id='ebay-f-trash']/a"