# URL = "https://www.ebay.com/"
LoginBtn = "//*[@id='gh-ug']/a"
LoginUsername = "//*[@id='userid']"
LoginPassword = "//*[@id='pass']"
NotRememberPass = "//button[@id='webauthn-maybe-later-link']"
GetSecurityCodeByText = "//*[@id='smsWithCode-btn']"
VerifyBtn = "//*[@id='verify-btn']"