PriceSneaker = "(//ul[@class='srp-results srp-grid clearfix']//div[@class='s-item__image'])[1]//img[@class='s-item__image-img']"
AddToCart = "//*[@class='u-cb  ']/span[not(starts-with(@style,'display:'))]/a"
InputText = "//input[@class='gh-tb ui-autocomplete-input']"
GridView = "//span[@class='expand-btn__cell']//*[@class='icon icon--filter-gallery-small']"
ItemsPerPage = "//*[@class='srp-results srp-grid clearfix']/li[starts-with(@class,'s-item')]"
RadioBuyingFormatChecked = "//*[@class='x-refine__select__svg']//input[@aria-label='All Listings' and @checked]"
RadioItemFormatChecked = "//*[@class='x-refine__select__svg']//input[@aria-label='Default' and @checked]"
USShoesSize = "//*[@aria-label='see all - US Shoe Size - opens dialog']"
AllFilter = "//*[@role='tab']"
CheckboxChoosed = "//*[@class='x-overlay__wrapper--right']//input[@checked]"
GridView = "//*[@class='icon icon--filter-gallery-small']/parent::span"
Settings = "//*[@class='icon icon--settings']/parent::span"
ThumbnailLarge = "//input[@id='cust-thumbSize-3' and @checked]"
OpenInNewTab = "//*[@id='cust-openVi-0' and @checked]"
CloseCustomize = "//*[@class='icon-btn lightbox-dialog__close' and @aria-label='Close']"
FirstItem = "(//ul[@class='srp-results srp-grid clearfix']//div[@class='s-item__image'])[1]//img"
AllCategory = "//select[@class='gh-sb ']/option"
TitleName = "//h1"
